name: slack-backup

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: kuboon/gsheet-slack-logger@main
        with:
          timezone: 'Asia/Tokyo'
          slackToken: ${{ secrets.SLACK_TOKEN }}
          googleClientEmail: slack-logger@kuboon-dev.iam.gserviceaccount.com
          googlePrivateKey: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          folderId: 1p0ZSVps76fWoLpfnE9y5tYHkCK18yVeW
          autoJoin: true
          skipChannels: CU3M2BLQ1 CTPLAAA02
