name: slack-backup

on:
  schedule:
    - cron:  '11 9 1 * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: kuboon/gsheet-slack-logger@main
        with:
          timezone: 'Asia/Tokyo'
          slack-token: ${{ secrets.SLACK_TOKEN }}
          google-client-email: slack-logger@kuboon-dev.iam.gserviceaccount.com
          google-private-key: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          folder-id: 1p0ZSVps76fWoLpfnE9y5tYHkCK18yVeW
 
